This is an overview of how to interact with the hdf5 file for you to practice with. This is most of the properties associated with the halos in the test simulation, but not all of the ones I've calculated. I've talked to John, and you'll ultimately be putting all of this on a website. The goal is to get familiar with everything here first. 

It would be helpful to me if you let me know if you think of the names of any of my attributes or datasets don't make sense because I want them to make sense to anybody reading the code, but right now, they are tailored to me. As always, let me know if anything doesn't make sense, and we can talk about all of this in our next meeting! 

In [11]:
#the imports you need to work this
import h5py
import numpy as np

In [12]:
#this opens the file and calls it f
#the a allows you to append to file
f = h5py.File("final_dataset_halo_catalog.hdf5", "a")

In [3]:
#this shows all my halo datasets in the file
f.keys()

<KeysViewHDF5 ['halo_0', 'halo_1', 'halo_13', 'halo_2', 'halo_3', 'halo_32', 'halo_49', 'halo_57', 'halo_63', 'halo_8', 'halo_99']>

In [4]:
#this is how you open an attribute, which in our case is a specific value of some quality of the halo
#for example, this one is the redshift that this output of the halo is at
f['halo_0'].attrs['current_redshift']

11.181356517874

In [5]:
#this lists all of the attributes I have saved for halo_0 in the hdf5 file
f['halo_0'].attrs.keys()

<KeysViewHDF5 ['SFE', 'SFR_100Myr', 'SFR_10Myr', 'current_redshift', 'filename', 'gas_fraction', 'halo_ID', 'last_major_merger', 'last_major_merger_halo_mass', 'sSFR_100Myr', 'sSFR_10Myr', 'specific_stellar_angular_momentum', 'total_DM_mass', 'total_HII_mass', 'total_HI_mass', 'total_bh_particles', 'total_cold_gas_mass', 'total_gas_mass', 'total_mass', 'total_pop3', 'total_pop3_mass', 'total_star_particles', 'total_stellar_mass', 'unique_desc_halo_ID', 'unique_desc_subhalo_ID', 'unique_halo_ID', 'unique_subhalo_ID', 'virial_radius']>

In [6]:
#this is how you open a dataset, which in our case is a set of numbers associated with the halo
#for example, this shows the mass of all of the Pop III (early universe, metal free) stars in the halo at this output
f['halo_0/pop3_stellar_masses/'][:]

array([6.62352608e+14, 3.33838606e+14, 3.69972745e+14, 5.70977469e+14,
       1.85103319e+35, 3.88832345e+15, 6.77653787e+14, 4.81095204e+14,
       8.13495141e+34, 3.57513606e+14, 8.22836639e+34, 8.13494422e+34,
       8.22835535e+34, 1.11998571e+35, 5.27115070e+14, 1.78870711e+35,
       4.81091817e+14, 3.88834843e+15])

In [46]:
#this lists all of the datasets I have saved for halo_0 in the hdf5 file
f['halo_0'].keys()

<KeysViewHDF5 ['angular_momentum', 'bh_particle_IDs', 'gas_mass', 'metallicity_fraction', 'photons_1e4', 'photons_1e5', 'photons_1e6', 'photons_1e7', 'pop3_stellar_masses', 'position', 'star_particle_IDs', 'stellar_age', 'stellar_angular_momentum', 'stellar_masses', 'stellar_positons', 'stellar_velocities']>

In [10]:
#Always close a file once you're finished using it, otherwise it can cause the file to be corrupted or unopenable in the fiture
f.close()

In [14]:
f['halo_0/star_particle_IDs'][:]

array([738913., 739347., 739348., 739339., 739340., 739341., 739342.,
       739343., 739345., 739346., 738872.])

In [16]:
f['halo_0/pop3_stellar_masses'][:]

array([6.62352608e+14, 3.33838606e+14, 3.69972745e+14, 5.70977469e+14,
       1.85103319e+35, 3.88832345e+15, 6.77653787e+14, 4.81095204e+14,
       8.13495141e+34, 3.57513606e+14, 8.22836639e+34, 8.13494422e+34,
       8.22835535e+34, 1.11998571e+35, 5.27115070e+14, 1.78870711e+35,
       4.81091817e+14, 3.88834843e+15])

In [23]:
f['halo_0/photons_1e4']

<HDF5 group "/halo_0/photons_1e4" (0 members)>