In [1]:
import h5py
import numpy as np
import ytree
import yt
import unyt

In [2]:
f = h5py.File("final_dataset_halo_catalog.hdf5", "a")
a = ytree.load('/storage/home/hcoda1/7/shardin31/p-jw254-0/Research/Powderday/powderday/arbor/arbor.h5')
a.field_list

['scale_factor',
 'uid',
 'desc_scale',
 'desc_uid',
 'num_prog',
 'pid',
 'upid',
 'desc_pid',
 'phantom',
 'sam_Mvir',
 'mass',
 'virial_radius',
 'scale_radius',
 'velocity_dispersion',
 'mmp?',
 'scale_of_last_MM',
 'vmax',
 'position_x',
 'position_y',
 'position_z',
 'velocity_x',
 'velocity_y',
 'velocity_z',
 'angular_momentum_x',
 'angular_momentum_y',
 'angular_momentum_z',
 'spin_parameter',
 'Breadth_first_ID',
 'Depth_first_ID',
 'Tree_root_ID',
 'halo_id',
 'Snap_idx',
 'Next_coprogenitor_depthfirst_ID',
 'Last_progenitor_depthfirst_ID',
 'Last_mainleaf_depthfirst_ID',
 'Tidal_Force',
 'Tidal_ID',
 'Rs_Klypin',
 'Mvir_all',
 'M200b',
 'M200c',
 'M500c',
 'M2500c',
 'Xoff',
 'Voff',
 'Spin_Bullock',
 'b_to_a',
 'c_to_a',
 'A[x]',
 'A[y]',
 'A[z]',
 'b_to_a(500c)',
 'c_to_a(500c)',
 'A[x](500c)',
 'A[y](500c)',
 'A[z](500c)',
 'T_|U|',
 'M_pe_Behroozi',
 'M_pe_Diemer',
 'Type',
 'SM',
 'Gas',
 'BH_Mass',
 'total_stellar_angular_momentum',
 'stellar_mass',
 'gas_mass',
 'tot

In [3]:
filename = '/storage/home/hcoda1/0/jw254/data/SG64-2020/DD0125/output_0125'
ds = yt.load(filename)

def p2(pfilter, data):
    return (data[('nbody', 'particle_type')] == 7)
yt.add_particle_filter(function=p2, name='p2', requires=['particle_mass', 'particle_type'])

ds.add_particle_filter("p2")

def p3(pfilter, data):
    return ((data[('nbody', 'particle_type')] == 5) & (data[('nbody', 'particle_mass')].in_units('Msun') < 1e-10)) \
        |  ((data[('nbody', 'particle_type')] == 1) & (data[('nbody', 'creation_time')] > 0) & \
            (data[('nbody', 'particle_mass')].in_units('Msun') > 1)) \
        |  ((data[('nbody', 'particle_type')] == 5) & (data[('nbody', 'particle_mass')].in_units('Msun') > 1e-3))
yt.add_particle_filter(function=p3, name='p3',
                requires=['particle_mass', 'particle_type', 'creation_time'])

ds.add_particle_filter("p3")

def p3_bh(pfilter, data):
    return (data[('nbody', 'particle_type')] == 1) & (data[('nbody', 'creation_time')] > 0) & \
        (data[('nbody', 'particle_mass')].in_units('Msun') > 1e-3)
yt.add_particle_filter(function=p3_bh, name='p3_bh', requires=['creation_time', 'particle_mass', 'particle_type'])

ds.add_particle_filter("p3_bh")

ds.field_list

yt : [INFO     ] 2024-06-12 15:01:26,499 Parameters: current_time              = 75.89987395114
yt : [INFO     ] 2024-06-12 15:01:26,502 Parameters: domain_dimensions         = [64 64 64]
yt : [INFO     ] 2024-06-12 15:01:26,505 Parameters: domain_left_edge          = [0. 0. 0.]
yt : [INFO     ] 2024-06-12 15:01:26,507 Parameters: domain_right_edge         = [1. 1. 1.]
yt : [INFO     ] 2024-06-12 15:01:26,509 Parameters: cosmological_simulation   = 1
yt : [INFO     ] 2024-06-12 15:01:26,510 Parameters: current_redshift          = 11.181356517874
yt : [INFO     ] 2024-06-12 15:01:26,512 Parameters: omega_lambda              = 0.6889
yt : [INFO     ] 2024-06-12 15:01:26,514 Parameters: omega_matter              = 0.3111
yt : [INFO     ] 2024-06-12 15:01:26,515 Parameters: omega_radiation           = 0
yt : [INFO     ] 2024-06-12 15:01:26,517 Parameters: hubble_constant           = 0.6766
Parsing Hierarchy : 100%|██████████| 777/777 [00:00<00:00, 14791.94it/s]
yt : [INFO     ] 2024-06-12 

[('all', 'creation_time'),
 ('all', 'dynamical_time'),
 ('all', 'metallicity_fraction'),
 ('all', 'particle_index'),
 ('all', 'particle_mass'),
 ('all', 'particle_position_x'),
 ('all', 'particle_position_y'),
 ('all', 'particle_position_z'),
 ('all', 'particle_type'),
 ('all', 'particle_velocity_x'),
 ('all', 'particle_velocity_y'),
 ('all', 'particle_velocity_z'),
 ('enzo', 'DII_Density'),
 ('enzo', 'DI_Density'),
 ('enzo', 'Dark_Matter_Density'),
 ('enzo', 'Density'),
 ('enzo', 'Electron_Density'),
 ('enzo', 'GasEnergy'),
 ('enzo', 'H2II_Density'),
 ('enzo', 'H2II_kdiss'),
 ('enzo', 'H2I_Density'),
 ('enzo', 'H2I_kdiss'),
 ('enzo', 'HDI_Density'),
 ('enzo', 'HII_Density'),
 ('enzo', 'HI_Density'),
 ('enzo', 'HI_kph'),
 ('enzo', 'HM_Density'),
 ('enzo', 'HM_kph'),
 ('enzo', 'HeIII_Density'),
 ('enzo', 'HeII_Density'),
 ('enzo', 'HeII_kph'),
 ('enzo', 'HeI_Density'),
 ('enzo', 'HeI_kph'),
 ('enzo', 'Metal_Density'),
 ('enzo', 'PhotoGamma'),
 ('enzo', 'RadAccel1'),
 ('enzo', 'RadAccel2

In [4]:
def halo_exists(halo_name, file):
    if halo_name in file:
        del file[halo_name]
        dset = f.create_group(halo_name)
        return dset
    else:
        dset = f.create_group(halo_name)
        return dset

In [10]:
for i in range(0, a.size, 1):
    if a['stellar_mass'][i] != 0:
        radius = ds.quan(a['virial_radius'][i], 'kpccm')
        radius = radius.to('kpc')
        center = a['position'][i]
        ad = ds.sphere(center, radius)
        
        #dset = f.create_group("halo_"+str(i))
        dset = halo_exists("halo_"+str(i), f)
        
        dset.attrs['total_stellar_mass'] = a['stellar_mass'][i]
        dset.attrs['virial_radius'] = a['virial_radius'][i]
        dset.attrs['total_DM_mass'] = a['mass'][i]
        dset.attrs['SFE'] = a['stellar_mass'][i] / a['mass'][i]
        dset.attrs['total_gas_mass'] = a['gas_mass'][i]
        total_mass = a['mass'][i]+a['gas_mass'][i]+a['stellar_mass'][i]
        dset.attrs['total_mass'] = total_mass
        dset.attrs['gas_fraction'] = a['gas_mass'][i]/total_mass
        dset.attrs['current_redshift'] = ds.current_redshift
        dset.attrs['total_pop3'] = ad['p3', 'particle_ones'].sum()
        dset.attrs['total_pop3_mass'] = a['total_pop3_mass'][i]
        dset.attrs['total_cold_gas_mass'] = a['total_cold_gas_mass'][i]
        dset.attrs['total_HI_mass'] = a['total_HI_mass'][i]
        dset.attrs['total_HII_mass'] = a['total_HII_mass'][i]
        dset.attrs['halo_ID'] = a['halo_id'][i]
        dset.attrs['unique_halo_ID'] = a['uid'][i]
        dset.attrs['unique_subhalo_ID'] = a['pid'][i]
        dset.attrs['unique_desc_halo_ID'] = a['desc_uid'][i]
        dset.attrs['unique_desc_subhalo_ID'] = a['desc_pid'][i]
        dset.attrs['total_star_particles'] = ad['p2', 'particle_ones'].sum()
        dset.attrs['total_bh_particles'] = ad['p3_bh', 'particle_ones'].sum()
        dset.attrs['filename'] = filename
        SFR_10 = a["stellar_mass_10Myr"][i] / (10 * unyt.Myr)
        SFR_100 = a["stellar_mass_100Myr"][i] / (100 * unyt.Myr)
        dset.attrs['SFR_10Myr'] = SFR_10
        dset.attrs['SFR_100Myr'] = SFR_100
        dset.attrs['sSFR_10Myr'] = SFR_10 / a['stellar_mass'][i]
        dset.attrs['sSFR_100Myr'] = SFR_100 / a['stellar_mass'][i]
        dset.attrs['specific_stellar_angular_momentum'] = a['total_stellar_angular_momentum'][i].to('Msun*pc*km/s') / a['stellar_mass'][i]
        dset.attrs['last_major_merger'] = a['scale_of_last_MM'][i]
        for x in range(0, a[i]['prog', 'scale_factor'].size, 1):
            if a['scale_of_last_MM'][i] == a[i]['prog', 'scale_factor'][x]:
                dset.attrs['last_major_merger_halo_mass'] = a['mass'][x]
                print(x)
        
        
        dset.create_dataset('position', data=a['position'][i])
        dset.create_dataset('angular_momentum', data=a['angular_momentum'][i])
        dset.create_dataset('stellar_age', data=ad["p2", "age"])
        dset.create_dataset('metallicity_fraction', data=ad["p2", "metallicity_fraction"])
        dset.create_dataset('stellar_masses', data=ad["p2", "particle_mass"])
        dset.create_dataset('pop3_stellar_masses', data=ad["p3", "particle_mass"])
        dset.create_dataset('gas_mass', data=ad['gas', 'mass'])
        dset.create_dataset('star_particle_IDs', data=ad['p2', 'particle_index'])
        dset.create_dataset('bh_particle_IDs', data=ad['p3_bh', 'particle_index'])
        dset.create_dataset('stellar_positons', data=ad["p2", "particle_position"])
        dset.create_dataset('stellar_velocities', data=ad["p2", "particle_velocity"])
        dset.create_dataset('stellar_angular_momentum', data=ad["p2", "particle_angular_momentum"])
        
        
        dset2 = dset.create_group("photons_1e4")
        dset2 = dset.create_group('photons_1e5')
        dset2 = dset.create_group('photons_1e6')
        dset2 = dset.create_group('photons_1e7')
#         grp1 = dset2.create_dataset("SED", (10, 10), maxshape=(None, None))
#         grp2 = dset2.create_dataset('image', (10, 10), maxshape=(None, None))

64
70
93
96
57
64
40
7
15
21
11


In [14]:
f.keys()

<KeysViewHDF5 ['halo_0', 'halo_1', 'halo_13', 'halo_2', 'halo_3', 'halo_32', 'halo_49', 'halo_57', 'halo_63', 'halo_8', 'halo_99']>

In [6]:
f.close()

In [39]:
del f['halo_49']
dset2.name

ValueError: Invalid location identifier (invalid location identifier)

In [4]:
a["stellar_mass"]

unyt_array([10498.53222656,  3535.85205078,  2097.26025391,
             1714.16357422,     0.     ,     0.     ,     0.     ,
                0.     ,  3232.9921875,     0.     ,     0.     ,
                0.     ,     0.     ,  2320.53027344,     0.     ,
                0.     ,     0.     ,     0.     ,     0.     ,
                0.     ,     0.     ,     0.     ,     0.     ,
                0.     ,     0.     ,     0.     ,     0.     ,
                0.     ,     0.     ,     0.     ,     0.     ,
                0.     ,  1410.24609375,     0.     ,     0.     ,
                0.     ,     0.     ,     0.     ,     0.     ,
                0.     ,     0.     ,     0.     ,     0.     ,
                0.     ,     0.     ,     0.     ,     0.     ,
                0.     ,     0.     ,  7978.07763672,     0.     ,
                0.     ,     0.     ,     0.     ,     0.     ,
                0.     ,     0.     ,   687.01416016,     0.     ,
                0.     ,   

In [8]:
f['halo_0/']

<HDF5 group "/halo_0" (9 members)>

In [22]:
f['halo_0'].attrs['current_redshift']

11.181356517874

In [39]:
f['halo_1'].attrs['last_major_merger_halo_mass']

420780.38

In [11]:
print(f['halo_0/10000'])

KeyError: 'Unable to open object (message type not found)'

In [7]:
a['total_stellar_angular_momentum'][0]

unyt_quantity(1.45784584e+63, 'cm**2*g/s')

In [27]:
ds.all_data()["age"][34]

unyt_quantity(5.35592024e+11, 'yr')

In [17]:
f['halo_0/photons_1e4']

<HDF5 group "/halo_0/photons_1e4" (0 members)>

In [17]:
mass = np.empty(a.size)
time = np.empty(a.size)

for i in range(0, a.size):
    mass[i] = a[i]["mass"]
    time[i] = a[i]["time"]

203


In [29]:
f['halo_0/position/'][:]

array([0.49441326, 0.51073015, 0.49368903], dtype=float32)

In [8]:
a["virial_radius"].size

203

In [9]:
a['mass']

unyt_array([7.94708800e+07, 4.64824120e+07, 3.14070340e+07,
            5.77446050e+06, 3.39787175e+06, 3.28111150e+06,
            3.19391075e+06, 2.81998225e+06, 2.20957725e+06,
            2.19479750e+06, 2.14898025e+06, 2.03517588e+06,
            2.03074188e+06, 1.95536500e+06, 1.91545962e+06,
            1.85929650e+06, 1.84747262e+06, 1.75288200e+06,
            1.54596512e+06, 1.54596512e+06, 1.53414125e+06,
            1.52379538e+06, 1.51049362e+06, 1.43910725e+06,
            1.39136862e+06, 1.35973988e+06, 1.34791600e+06,
            1.30416788e+06, 1.25051725e+06, 1.20085725e+06,
            1.18504288e+06, 1.14528525e+06, 1.13080100e+06,
            1.10567538e+06, 1.03414131e+06, 1.01433638e+06,
            9.80490688e+05, 9.30978438e+05, 9.13094875e+05,
            8.81318375e+05, 8.59444250e+05, 8.47620438e+05,
            8.45551250e+05, 8.33727438e+05, 8.29736938e+05,
            7.80076875e+05, 7.26426250e+05, 7.18592938e+05,
            7.02630812e+05, 6.94649688e+

In [26]:
f['halo_0/stellar_age/'][:]

KeyError: "Unable to open object (object 'gas_mass' doesn't exist)"

In [16]:
f['halo_13'].attrs['SFR_10Myr']

0.0

In [21]:
f['halo_0/pop3_stellar_masses/'][:]

array([6.62352608e+14, 3.33838606e+14, 3.69972745e+14, 5.70977469e+14,
       1.85103319e+35, 3.88832345e+15, 6.77653787e+14, 4.81095204e+14,
       8.13495141e+34, 3.57513606e+14, 8.22836639e+34, 8.13494422e+34,
       8.22835535e+34, 1.11998571e+35, 5.27115070e+14, 1.78870711e+35,
       4.81091817e+14, 3.88834843e+15])

In [9]:
a['total_pop3_mass'][0]

unyt_quantity(403.95914687, 'Msun')

In [11]:
a['stellar_mass'][0]

unyt_quantity(10498.53222656, 'Msun')

In [8]:
f['halo_0'].attrs['specific_stellar_angular_momentum']

6.983542790349967e+25

In [30]:
f.attrs['halo_0/SFR']

KeyError: "Can't open attribute (can't locate attribute: 'halo_0/SFE')"

In [14]:
a["desc_uid"]

array([-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1])

In [10]:
radius = ds.quan(a['virial_radius'][0], 'kpccm')
radius = radius.to('kpc')
center = a['position'][0]
ad = ds.sphere(center, radius)

ad['p2', 'age'].to('Myr')

unyt_array([ 99.23255809,  39.94049007,  35.30474612,  48.20399029,
             47.51374019,  47.00589892,  45.79622204,  45.13948389,
             43.54732764,  42.52933858, 213.22005466], 'Myr')

In [41]:
f['halo_0/star_particle_IDs'][:]

array([738913., 739347., 739348., 739339., 739340., 739341., 739342.,
       739343., 739345., 739346., 738872.])

In [13]:
f['halo_0'].attrs['unique_halo_ID']

26720

In [31]:
a["stellar_mass_10Myr"][99]

unyt_quantity(0., dtype=float32, units='Msun')

In [37]:
for x in a[0]['prog', 'scale_factor']:
    if x = a['scale']

array([0.08209, 0.08197, 0.08184, 0.08171, 0.08159, 0.08146, 0.08133,
       0.0812 , 0.08108, 0.08095, 0.08082, 0.0807 , 0.08057, 0.08044,
       0.08031, 0.08018, 0.08005, 0.07993, 0.0798 , 0.07967, 0.07954,
       0.07941, 0.07929, 0.07916, 0.07903, 0.0789 , 0.07877, 0.07864,
       0.07851, 0.07838, 0.07825, 0.07812, 0.07799, 0.07786, 0.07773,
       0.0776 , 0.07747, 0.07734, 0.07721, 0.07708, 0.07695, 0.07682,
       0.07669, 0.07656, 0.07643, 0.0763 , 0.07616, 0.07603, 0.0759 ,
       0.07524, 0.07458, 0.07391, 0.07324, 0.07257, 0.0719 , 0.07122,
       0.07054, 0.06986, 0.06917, 0.06848, 0.06779, 0.06709, 0.06639,
       0.06568, 0.06497, 0.06426, 0.06354, 0.06282, 0.0621 , 0.06137,
       0.06063, 0.05989, 0.05915, 0.0584 , 0.05765, 0.05689, 0.05613,
       0.05536, 0.05459, 0.05381, 0.05303, 0.05224, 0.05144, 0.05064,
       0.04983, 0.04902, 0.0482 , 0.04784, 0.04737, 0.04653, 0.04569,
       0.04484], dtype=float32)

In [11]:
print(a['scale_of_last_MM'][1])
print(a[1]['prog', 'scale_factor'][70])

0.06063
0.06063
