In [1]:
import numpy as np
import scipy.ndimage
import math
import yt
from astropy.io import fits
import sys
np.set_printoptions(threshold=sys.maxsize)

In [2]:
filename = '/storage/home/hcoda1/0/jw254/data/RS-RP/RD0041/RedshiftOutput0041'
ds = yt.load(filename)
r = ds.current_redshift
filter_r = (1 + r)

yt : [INFO     ] 2025-03-10 23:33:40,982 Parameters: current_time              = 12.75658720606
yt : [INFO     ] 2025-03-10 23:33:40,983 Parameters: domain_dimensions         = [512 512 512]
yt : [INFO     ] 2025-03-10 23:33:40,986 Parameters: domain_left_edge          = [0. 0. 0.]
yt : [INFO     ] 2025-03-10 23:33:40,987 Parameters: domain_right_edge         = [1. 1. 1.]
yt : [INFO     ] 2025-03-10 23:33:40,988 Parameters: cosmological_simulation   = 1
yt : [INFO     ] 2025-03-10 23:33:40,989 Parameters: current_redshift          = 14.999999224523
yt : [INFO     ] 2025-03-10 23:33:40,989 Parameters: omega_lambda              = 0.734
yt : [INFO     ] 2025-03-10 23:33:40,990 Parameters: omega_matter              = 0.266
yt : [INFO     ] 2025-03-10 23:33:40,990 Parameters: omega_radiation           = 0.0
yt : [INFO     ] 2025-03-10 23:33:40,990 Parameters: hubble_constant           = 0.71


In [8]:
F070W = []

with open('/storage/home/hcoda1/7/shardin31/p-jw254-0/Research/Powderday/powderday/filters/mean_throughputs/F070W_mean_system_throughput.txt', 'r') as f:
    F070W = [[float(x) for x in line.split()] for line in f]
    
F070W_nparray = np.asarray(F070W)

#print(F070W_nparray)

i = len(F070W_nparray)

F070W_smoothedarray = scipy.ndimage.gaussian_filter(F070W_nparray, sigma = (10, 0))
    
N = len(F070W_smoothedarray)/10

F070W_downsizedarray = F070W_smoothedarray[::math.ceil(N)]

print(F070W_downsizedarray)
    
F070W_downsizedarray[:,0] = F070W_downsizedarray[:,0]/filter_r

print(F070W_downsizedarray)

with open('/storage/home/hcoda1/7/shardin31/p-jw254-0/Research/Powderday/powderday/filters/mean_throughputs_downsized/F070W_downsized.txt', 'w') as f:
    f.write('\n'.join('\t'.join('%0.8f' %x for x in y) for y in F070W_downsizedarray))

[[5.55640396e-01 2.50020940e-09]
 [5.79153930e-01 1.99063866e-04]
 [6.10150024e-01 6.90261064e-02]
 [6.41150024e-01 1.75361324e-01]
 [6.72150024e-01 2.08671880e-01]
 [7.03150024e-01 2.34518687e-01]
 [7.34150024e-01 2.63808035e-01]
 [7.65150024e-01 2.69085887e-01]
 [7.96150024e-01 2.61989901e-02]
 [8.27104037e-01 1.48260202e-05]]
[[3.47275265e-02 2.50020940e-09]
 [3.61971224e-02 1.99063866e-04]
 [3.81343784e-02 6.90261064e-02]
 [4.00718785e-02 1.75361324e-01]
 [4.20093786e-02 2.08671880e-01]
 [4.39468787e-02 2.34518687e-01]
 [4.58843787e-02 2.63808035e-01]
 [4.78218788e-02 2.69085887e-01]
 [4.97593789e-02 2.61989901e-02]
 [5.16940048e-02 1.48260202e-05]]


In [23]:
F070W_nparray = np.asarray(F070W)

#sigma = np.full((len(F070W_nparray), len(F070W_nparray[0])), 1e4/10)

F070W_smoothedarray = sp.ndimage.gaussian_filter(F070W_nparray, 1e4/10)
#F070W_averagearray1 = np.convolve(F070W_nparray[:, 0], 1e4//10, mode='same')
#F070W_averagearray = pylops.Smoothing2D(F070W_nparray, [1e4/10, 1e4/10], dtype="float64")
#F070W_averagearray = sp.signal.convolve2d(F070W_nparray, sigma, mode='full')

F070W_downsizedarray = sp.ndimage.zoom(F070W_smoothedarray, (0.05, 1), order=1)

# avg = F070W_smoothedarray.reshape()
# print(avg)

#F070W_downsizedarray_str = np.array2string(F070W_downsizedarray)

#b = '\n'.join('\t'.join('%f' %x for x in y) for y in F070W_downsizedarray)
#print(F070W_smoothedarray)
#print(F070W_downsizedarray)



NameError: name 'sp' is not defined

In [24]:
with open('/Users/samanthahardin/Research/Powderday/powderday/filters/mean_throughputs_downsized/F070W_output.txt', 'w') as f:
    f.write('\n'.join('\t'.join('%0.8f' %x for x in y) for y in F070W_downsizedarray))

FileNotFoundError: [Errno 2] No such file or directory: '/Users/samanthahardin/Research/Powderday/powderday/filters/mean_throughputs_downsized/F070W_output.txt'

In [48]:
F090W = []

with open('/storage/home/hcoda1/7/shardin31/p-jw254-0/Research/Powderday/powderday/filters/mean_throughputs/F090W_mean_system_throughput.txt', 'r') as f:
    F090W = [[float(x) for x in line.split()] for line in f]
    
F090W_nparray = np.asarray(F090W)

i = len(F090W_nparray)

F090W_smoothedarray = scipy.ndimage.gaussian_filter(F090W_nparray, sigma = (10, 0))

N = len(F090W_smoothedarray)/10

F090W_downsizedarray = F090W_smoothedarray[::math.ceil(N)]

print(F090W_downsizedarray)
    
F090W_downsizedarray[:,0] = F090W_downsizedarray[:,0]/filter_r

print(F090W_downsizedarray)

with open('/storage/home/hcoda1/7/shardin31/p-jw254-0/Research/Powderday/powderday/filters/mean_throughputs_downsized/F090W_downsized.txt', 'w') as f:
    f.write('\n'.join('\t'.join('%0.8f' %x for x in y) for y in F090W_downsizedarray))

[[7.55040360e-01 6.44613402e-07]
 [7.80551631e-01 2.61867299e-02]
 [8.13549988e-01 2.70776663e-01]
 [8.46549988e-01 3.01533920e-01]
 [8.79549988e-01 3.14612493e-01]
 [9.12549988e-01 3.24812341e-01]
 [9.45549988e-01 3.32612173e-01]
 [9.78549988e-01 3.38323498e-01]
 [1.01154999e+00 1.09879625e-01]
 [1.04453786e+00 3.84127138e-04]]
[[4.71900248e-02 6.44613402e-07]
 [4.87844793e-02 2.61867299e-02]
 [5.08468767e-02 2.70776663e-01]
 [5.29093768e-02 3.01533920e-01]
 [5.49718769e-02 3.14612493e-01]
 [5.70343770e-02 3.24812341e-01]
 [5.90968771e-02 3.32612173e-01]
 [6.11593772e-02 3.38323498e-01]
 [6.32218777e-02 1.09879625e-01]
 [6.52836194e-02 3.84127138e-04]]


In [49]:
F115W = []

with open('/storage/home/hcoda1/7/shardin31/p-jw254-0/Research/Powderday/powderday/filters/mean_throughputs/F115W_mean_system_throughput.txt', 'r') as f:
    F115W = [[float(x) for x in line.split()] for line in f]
    
F115W_nparray = np.asarray(F115W)

i = len(F115W_nparray)

F115W_smoothedarray = scipy.ndimage.gaussian_filter(F115W_nparray, sigma = (10, 0))

N = len(F115W_smoothedarray)/10

F115W_downsizedarray = F115W_smoothedarray[::math.ceil(N)]

print(F115W_downsizedarray)
    
F115W_downsizedarray[:,0] = F115W_downsizedarray[:,0]/filter_r

print(F115W_downsizedarray)

with open('/storage/home/hcoda1/7/shardin31/p-jw254-0/Research/Powderday/powderday/filters/mean_throughputs_downsized/F115W_downsized.txt', 'w') as f:
    f.write('\n'.join('\t'.join('%0.8f' %x for x in y) for y in F115W_downsizedarray))

[[9.75690384e-01 1.21277037e-04]
 [1.00720002e+00 1.20223040e-01]
 [1.04619995e+00 2.81069997e-01]
 [1.08519995e+00 2.76208530e-01]
 [1.12419995e+00 3.04091549e-01]
 [1.16319995e+00 3.53496491e-01]
 [1.20219995e+00 3.56897199e-01]
 [1.24119995e+00 3.87186606e-01]
 [1.28019995e+00 2.30934165e-01]
 [1.31919980e+00 1.77960452e-03]]
[[6.09806520e-02 1.21277037e-04]
 [6.29500045e-02 1.20223040e-01]
 [6.53875002e-02 2.81069997e-01]
 [6.78250002e-02 2.76208530e-01]
 [7.02625004e-02 3.04091549e-01]
 [7.27000005e-02 3.53496491e-01]
 [7.51375006e-02 3.56897199e-01]
 [7.75750007e-02 3.87186606e-01]
 [8.00125008e-02 2.30934165e-01]
 [8.24499912e-02 1.77960452e-03]]


In [50]:
F356W = []

with open('/storage/home/hcoda1/7/shardin31/p-jw254-0/Research/Powderday/powderday/filters/mean_throughputs/F356W_mean_system_throughput.txt', 'r') as f:
    F356W = [[float(x) for x in line.split()] for line in f]
    
F356W_nparray = np.asarray(F356W)

i = len(F356W_nparray)

F356W_smoothedarray = scipy.ndimage.gaussian_filter(F356W_nparray, sigma = (10, 0))

N = len(F356W_smoothedarray)/10

F356W_downsizedarray = F356W_smoothedarray[::math.ceil(N)]

print(F356W_downsizedarray)
    
F356W_downsizedarray[:,0] = F356W_downsizedarray[:,0]/filter_r

print(F356W_downsizedarray)

with open('/storage/home/hcoda1/7/shardin31/p-jw254-0/Research/Powderday/powderday/filters/mean_throughputs_downsized/F356W_downsized.txt', 'w') as f:
    f.write('\n'.join('\t'.join('%0.8f' %x for x in y) for y in F356W_downsizedarray))

[[2.99904517e+00 1.67648660e-04]
 [3.11729093e+00 1.50384144e-01]
 [3.24565792e+00 4.68344934e-01]
 [3.37402490e+00 5.05169653e-01]
 [3.50239189e+00 5.31579601e-01]
 [3.63075888e+00 5.54626902e-01]
 [3.75912586e+00 5.71665228e-01]
 [3.88749285e+00 5.67703265e-01]
 [4.01585984e+00 9.48073801e-02]
 [4.14422682e+00 6.86453394e-04]]
[[1.87440332e-01 1.67648660e-04]
 [1.94830693e-01 1.50384144e-01]
 [2.02853630e-01 4.68344934e-01]
 [2.10876567e-01 5.05169653e-01]
 [2.18899504e-01 5.31579601e-01]
 [2.26922441e-01 5.54626902e-01]
 [2.34945378e-01 5.71665228e-01]
 [2.42968315e-01 5.67703265e-01]
 [2.50991252e-01 9.48073801e-02]
 [2.59014189e-01 6.86453394e-04]]


In [51]:
F150W = []

with open('/storage/home/hcoda1/7/shardin31/p-jw254-0/Research/Powderday/powderday/filters/mean_throughputs/F150W_mean_system_throughput.txt', 'r') as f:
    F150W = [[float(x) for x in line.split()] for line in f]
    
F150W_nparray = np.asarray(F150W)

i = len(F150W_nparray)

F150W_smoothedarray = scipy.ndimage.gaussian_filter(F150W_nparray, sigma = (10, 0))

N = len(F150W_smoothedarray)/10

F150W_downsizedarray = F150W_smoothedarray[::math.ceil(N)]

print(F150W_downsizedarray)
    
F150W_downsizedarray[:,0] = F150W_downsizedarray[:,0]/filter_r

print(F150W_downsizedarray)

with open('/storage/home/hcoda1/7/shardin31/p-jw254-0/Research/Powderday/powderday/filters/mean_throughputs_downsized/F150W_downsized.txt', 'w') as f:
    f.write('\n'.join('\t'.join('%0.8f' %x for x in y) for y in F150W_downsizedarray))

[[1.25628041e+00 1.17123044e-05]
 [1.29979004e+00 7.97285855e-03]
 [1.35079004e+00 4.23958584e-01]
 [1.40179004e+00 4.45918159e-01]
 [1.45279004e+00 4.70526089e-01]
 [1.50379004e+00 4.81564173e-01]
 [1.55479004e+00 4.85729067e-01]
 [1.60579004e+00 5.02500395e-01]
 [1.65679004e+00 4.31573390e-01]
 [1.70779004e+00 2.32007955e-03]]
[[7.85175295e-02 1.17123044e-05]
 [8.12368814e-02 7.97285855e-03]
 [8.44243815e-02 4.23958584e-01]
 [8.76118817e-02 4.45918159e-01]
 [9.07993818e-02 4.70526089e-01]
 [9.39868820e-02 4.81564173e-01]
 [9.71743822e-02 4.85729067e-01]
 [1.00361882e-01 5.02500395e-01]
 [1.03549382e-01 4.31573390e-01]
 [1.06736883e-01 2.32007955e-03]]


In [42]:
F444W = []

with open('/storage/home/hcoda1/7/shardin31/p-jw254-0/Research/Powderday/powderday/filters/mean_throughputs/F444W_mean_system_throughput.txt', 'r') as f:
    F444W = [[float(x) for x in line.split()] for line in f]
    
F444W_nparray = np.asarray(F444W)

#print(F444W_nparray)

i = len(F444W_nparray)

F444W_smoothedarray = scipy.ndimage.gaussian_filter(F444W_nparray, sigma = (10,0))

#print(F444W_smoothedarray)
    
N = len(F444W_smoothedarray)/10

F444W_downsizedarray = F444W_smoothedarray[::math.ceil(N)]

#print(F444W_downsizedarray[:,0])
    
F444W_downsizedarray[:,0] = F444W_downsizedarray[:,0]/filter_r

#print(F444W_downsizedarray)

with open('/storage/home/hcoda1/7/shardin31/p-jw254-0/Research/Powderday/powderday/filters/mean_throughputs_downsized/F444W_downsized.txt', 'w') as f:
    f.write('\n'.join('\t'.join('%0.8f' %x for x in y) for y in F444W_downsizedarray))

In [52]:
F200W = []

with open('/storage/home/hcoda1/7/shardin31/p-jw254-0/Research/Powderday/powderday/filters/mean_throughputs/F200W_mean_system_throughput.txt', 'r') as f:
    F200W = [[float(x) for x in line.split()] for line in f]
    
F200W_nparray = np.asarray(F200W)

i = len(F200W_nparray)

F200W_smoothedarray = scipy.ndimage.gaussian_filter(F200W_nparray, sigma = (10, 0))
    
N = len(F200W_smoothedarray)/10

F200W_downsizedarray = F200W_smoothedarray[::math.ceil(N)]

print(F200W_downsizedarray)
    
F200W_downsizedarray[:,0] = F200W_downsizedarray[:,0]/filter_r

print(F200W_downsizedarray)

with open('/storage/home/hcoda1/7/shardin31/p-jw254-0/Research/Powderday/powderday/filters/mean_throughputs_downsized/F200W_downsized.txt', 'w') as f:
    f.write('\n'.join('\t'.join('%0.8f' %x for x in y) for y in F200W_downsizedarray))

[[1.69289040e+00 1.63261591e-04]
 [1.74740002e+00 1.57648443e-01]
 [1.80940002e+00 5.15398225e-01]
 [1.87140002e+00 5.24237243e-01]
 [1.93340002e+00 5.32015021e-01]
 [1.99540002e+00 5.31977480e-01]
 [2.05739992e+00 5.32380891e-01]
 [2.11939990e+00 5.33599144e-01]
 [2.18139990e+00 5.14771841e-01]
 [2.24339990e+00 8.77209754e-02]]
[[1.05805655e-01 1.63261591e-04]
 [1.09212507e-01 1.57648443e-01]
 [1.13087507e-01 5.15398225e-01]
 [1.16962507e-01 5.24237243e-01]
 [1.20837507e-01 5.32015021e-01]
 [1.24712508e-01 5.31977480e-01]
 [1.28587501e-01 5.32380891e-01]
 [1.32462500e-01 5.33599144e-01]
 [1.36337501e-01 5.14771841e-01]
 [1.40212501e-01 8.77209754e-02]]


In [53]:
F277W = []

with open('/storage/home/hcoda1/7/shardin31/p-jw254-0/Research/Powderday/powderday/filters/mean_throughputs/F277W_mean_system_throughput.txt', 'r') as f:
    F277W = [[float(x) for x in line.split()] for line in f]
    
F277W_nparray = np.asarray(F277W)

i = len(F277W_nparray)

F277W_smoothedarray = scipy.ndimage.gaussian_filter(F277W_nparray, sigma = (10, 0))

N = len(F277W_smoothedarray)/10

F277W_downsizedarray = F277W_smoothedarray[::math.ceil(N)]
    
print(F277W_downsizedarray)
    
F277W_downsizedarray[:,0] = F277W_downsizedarray[:,0]/filter_r

print(F277W_downsizedarray)
    
with open('/storage/home/hcoda1/7/shardin31/p-jw254-0/Research/Powderday/powderday/filters/mean_throughputs_downsized/F277W_downsized.txt', 'w') as f:
    f.write('\n'.join('\t'.join('%0.8f' %x for x in y) for y in F277W_downsizedarray))

[[2.30764448e+00 4.34877561e-06]
 [2.41994635e+00 2.04143746e-01]
 [2.54124391e+00 3.91678646e-01]
 [2.66254147e+00 4.07791719e-01]
 [2.78383903e+00 4.10533314e-01]
 [2.90513659e+00 4.25262264e-01]
 [3.02643415e+00 4.35799298e-01]
 [3.14773171e+00 1.15527365e-01]
 [3.26902927e+00 6.73924317e-04]
 [3.39032683e+00 3.23511064e-05]]
[[1.44227787e-01 4.34877561e-06]
 [1.51246654e-01 2.04143746e-01]
 [1.58827752e-01 3.91678646e-01]
 [1.66408850e-01 4.07791719e-01]
 [1.73989948e-01 4.10533314e-01]
 [1.81571046e-01 4.25262264e-01]
 [1.89152144e-01 4.35799298e-01]
 [1.96733241e-01 1.15527365e-01]
 [2.04314339e-01 6.73924317e-04]
 [2.11895437e-01 3.23511064e-05]]


In [54]:
F110W = []

with fits.open('/storage/home/hcoda1/7/shardin31/p-jw254-0/Research/Powderday/powderday/filters/mean_throughputs/jwst_nirspec_f110w_trans.fits') as f:
    for row in f[1].data:
        F110W.append(list(row))
    
F110W_nparray = np.asarray(F110W)

i = len(F110W_nparray)

F110W_smoothedarray = scipy.ndimage.gaussian_filter(F110W_nparray, sigma = (10, 0))

N = len(F110W_smoothedarray)/10

F110W_downsizedarray = F110W_smoothedarray[::math.ceil(N)]

print(F110W_downsizedarray)
    
F110W_downsizedarray[:,0] = F110W_downsizedarray[:,0]/filter_r

print(F110W_downsizedarray)

with open('/storage/home/hcoda1/7/shardin31/p-jw254-0/Research/Powderday/powderday/filters/mean_throughputs_downsized/F110W_downsized.txt', 'w') as f:
    f.write('\n'.join('\t'.join('%0.8f' %x for x in y) for y in F110W_downsizedarray))

[[4.1487601e-01 4.8161155e-04]
 [7.0075965e-01 9.8156522e-04]
 [9.4898164e-01 5.1068015e-02]
 [1.1067986e+00 9.6948439e-01]
 [1.3448341e+00 7.9811983e-02]
 [1.6711327e+00 4.3106400e-03]
 [1.9659246e+00 4.5074052e-03]
 [2.3096020e+00 6.0502449e-03]
 [2.5790153e+00 5.1177409e-03]
 [2.8154290e+00 2.8883845e-03]]
[[2.59297527e-02 4.81611554e-04]
 [4.37974818e-02 9.81565216e-04]
 [5.93113564e-02 5.10680154e-02]
 [6.91749230e-02 9.69484389e-01]
 [8.40521380e-02 7.98119828e-02]
 [1.04445800e-01 4.31064004e-03]
 [1.22870296e-01 4.50740522e-03]
 [1.44350141e-01 6.05024491e-03]
 [1.61188468e-01 5.11774095e-03]
 [1.75964326e-01 2.88838451e-03]]


In [16]:
print(F070W_downsizedarray.size)

print(F277W_downsizedarray.size)

20
20


In [17]:
F070W_smoothedarray.size

608

In [18]:
F070W_nparray.size

608

In [19]:
print(F070W_downsizedarray.size)
print(F090W_downsizedarray.size)
print(F115W_downsizedarray.size)
print(F356W_downsizedarray.size)
print(F150W_downsizedarray.size)
print(F444W_downsizedarray.size)
print(F200W_downsizedarray.size)
print(F277W_downsizedarray.size)

20
20
20
20
20
20
20
20


In [51]:
N = len(F200W_smoothedarray)/10
print(N)
print(math.ceil(N))

61.8
62


In [43]:
N = len(F277W_smoothedarray)/10
print(N)

101.0
